INSERT INTO images (src, alt, class) VALUES
('oeuvre1.jpg', 'Composition abstraite bleue', 'standard'),
('oeuvre2.jpg', 'Sculpture métallique futuriste', 'large'),
('oeuvre3.jpg', 'Nature morte aux fruits', 'standard'),
('oeuvre4.jpg', 'Portrait expressionniste', 'large'),
('oeuvre5.jpg', 'Paysage montagneux', 'standard'),
('oeuvre6.jpg', 'Installation lumineuse', 'large'),
('oeuvre7.jpg', 'Dessin au fusain', 'standard'),
('oeuvre8.jpg', 'Graffiti urbain coloré', 'large'),
('oeuvre9.jpg', 'Aquarelle marine', 'standard'),
('oeuvre10.jpg', 'Série photographique noir et blanc', 'large'),
('oeuvre11.jpg', 'Mosaïque antique', 'standard'),
('oeuvre12.jpg', 'Peinture numérique', 'large'),
('oeuvre13.jpg', 'Calligraphie asiatique', 'standard'),
('oeuvre14.jpg', 'Sculpture sur bois', 'large'),
('oeuvre15.jpg', 'Abstraction géométrique', 'standard'),
('oeuvre16.jpg', 'Performance artistique', 'large'),
('oeuvre17.jpg', 'Miniature médiévale', 'standard'),
('oeuvre18.jpg', 'Céramique artisanale', 'large'),
('oeuvre19.jpg', 'Collage surréaliste', 'standard'),
('oeuvre20.jpg', 'Fresque murale', 'large'),
('oeuvre21.jpg', 'Estampe japonaise', 'standard'),
('oeuvre22.jpg', 'Art génératif algorithmique', 'large'),
('oeuvre23.jpg', 'Dessin botanique', 'standard'),
('oeuvre24.jpg', 'Mobile cinétique', 'large'),
('oeuvre25.jpg', 'Peinture', 'standard'),
('oeuvre26.jpg', 'Projection vidéo artistique', 'large');